version: '1.0'

services:
  app:
    image: your-dash-app-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - USE_AWS=False  # Set to False to use local resources
      - AWS_DEFAULT_REGION=us-east-2
      - S3_BUCKET_NAME=segbuilder
      - LOCAL_FOLDER=/app/local_storage
      - LOCAL_DB_FILE=/app/local_db.json
    volumes:
      - ./local_storage:/app/local_storage  # Mount local folder to container
      - ./local_db.json:/app/local_db.json  # Mount local DynamoDB file to container
    ports:
      - "8050:8050"
  web:
    build: .
    ports:
      - "4566:4566"